### ISSUE TITLE
T&F: unknown entity problem

### ISSUE THREAD

**Issue by csgrant00** [adsabs/ADSManualParser#28]
&#x200c; being converted to &zwnj; which does not get resolved.  Probably some kind of nbsp?

python run.py -p "/proj/ads/abstracts/data/T+F/TF.080823/ytrb20.v017.i02/17515831.2022.2139517.xml"  -t jats -f tf

**Comment by seasidesparrow** [comment]
I think it's the &zwnj; ("zero-width non joiner") which is apparently used in charsets with ligatures.  I'll play with it.

**Comment by seasidesparrow** [comment]
```
&#x200c; being converted to &zwnj
```

**Comment by seasidesparrow** [comment]
Fixed in #54
