### ISSUE TITLE
Reference Writer functionality

### ISSUE THREAD

**Issue by seasidesparrow** [adsabs/ADSManualParser#31]
The original adsabs-pyingest has the [pyingest.serializers.refwriter module](https://github.com/adsabs/adsabs-pyingest/blob/master/pyingest/serializers/refwriter.py) that takes the array of references from the output record, and writes them to a file with a specific (but very simple) format.  The part of this code that is challenging to reproduce is the dependency of the file location on the *publisher*, which is not necessarily clearly defined in the output record.  For example, ApJ is "published" by the American Astronomical Society, but the actual publisher is IOP.  Publisher data are slowly being made available via the `journals/summary` API endpoint and can be obtained from the issn embedded in the record.

ADSManualParser needs a handler for a record in the Ingest_Data_Model format that writes a formatted reference file with the required file extension and directory path.

**Comment by seasidesparrow** [comment]
Question for @ehenneken @csgrant00
- If we get a record via crossref but the publisher is one where we do special handling (e.g. IOP), do we write the references to a "crossref" file or an "iop" file?  Are we getting anything from Crossref that we wouldn't get from the publisher?

Question for all:
- I'm envisioning this being a transitional module to support classic, file-based data stores.  All of the file/path naming issues go away if/when we use a database for reference storage.  How much time do we want to put into refwriter versus developing a "pipeline" or equivalent for reference storage?

**Comment by ehenneken** [comment]
@seasidesparrow References from Crossref always go into a "crossref" file. In some cases we do not get references from the publisher, in which case Crossref will be the only source for reference data.

I think a database for reference data is still far far away. We should have a discussion with curators and the Dev Team about matters related to architecture

**Comment by seasidesparrow** [comment]
Following discussion, we are going to use the code in ADSIngestEnrichment to do the work of generating the data, and ADSManualParser will import refwriter from there.

**Comment by mugdhapolimera** [comment]
Picking this up in https://github.com/adsabs/ADSIngestEnrichment/issues/16
