### ISSUE TITLE
IUCr - not generating bibcode

### ISSUE THREAD

**Issue by csgrant00** [adsabs/ADSManualParser#36]
[venv.adsnest] adsnest-1014: python run.py -p "/proj/ads/abstracts/data/IUCR/AllPubMedXML/d-60-02355.xml" -t jats -f iucr.test
Couldnt make a bibcode: You're missing year and or bibstem -- no bibcode can be made!

**Comment by csgrant00** [comment]
The problem is a mismatch in epub issn and ppub issn, I think.  Records with this:
         <issn pub-type="epub">1399-0047</issn>
generate a bibcode, but records with this:
         <issn pub-type="epub">0907-4449</issn>

do not.  Can you add a check for either issn when trying to generate the bibcode?

**Comment by seasidesparrow** [comment]
Yes, you can tag additional entries as (for example)`ISSN_print2` or change the original to `ISSN_printX` and make a new record for the correct one

**Comment by seasidesparrow** [comment]
Those two ISSNs are valid for Acta Cristallographica D by the way.  The 0907 one is not showing up in the API, so it's not in journalsdb.  Is IUCr a publisher or ???  It's not a bibstem.
