### ISSUE TITLE
MDPI processing

### ISSUE THREAD

**Issue by seasidesparrow** [adsabs/ADSManualParser#45]

**Comment by seasidesparrow** [comment]
Parsing attempt made on 2023 Dec 05: `python mtt.py -p "/proj/ads/abstracts/data/MDPI/Galax/*.xml" -t jats -f mdpi_mtt.tag -w -r "./mtt/" -s jats`

Results are in `mdpi_mtt.tag` (classic record) and `mtt/Galax/*` (references)

Note: this is using the `seasidesparrow/ADSIngestEnrichment@ref_filenaming.20231121` branch of ADSIngestEnrichment

**Comment by seasidesparrow** [comment]
Slack thread from @csgrant00 (Jan 29, 2024): 

> Another "bug" - when there is only a collaboration as author, it is treated as an author, but the bibcode isn't being generated correctly (it gets a "." instead of an intial). e.g. /proj/ads/abstracts/data/MDPI/QBS/MDPI/QBS/qubs-03-00002.xml

> Mugdha Polimera (she/her) I would appreciate a github issue for this. I suspect this has to do with a recent collab/author update I made in the jats parser

What is the status of this issue?  Was the issue ever created in ADSIngestParser for parsers.jats? @csgrant00 @mugdhapolimera

**Comment by csgrant00** [comment]
https://github.com/adsabs/ADSManualParser/issues/50

*************************************************************************

 Carolyn Stern Grant              Astrophysics Data System (ADS)

 ***@***.***        Center for Astrophysics

 617-495-7154 (voicemail)      60 Garden Street  MS 83

 617-495-7356 fax                 Cambridge, MA  02138

*************************************************************************

**Comment by seasidesparrow** [comment]
This was traced to an ADSIngestParser issue, fixed in https://github.com/adsabs/ADSIngestEnrichment/pull/25
