### ISSUE TITLE
copernicus pdf link missing

### ISSUE THREAD

**Issue by csgrant00** [adsabs/ADSManualParser#48]
Output should include %I PDF: and the pdf link.

e.g. /proj/ads/abstracts/data/EGU/EGU.010724/acp-24-1-2024.xml

should output
%I DOI: 10.5194/acp-24-1-2024; PDF: https://acp.copernicus.org/articles/24/1/2024/acp-24-1-2024.pdf

and not just

%I DOI: 10.5194/acp-24-1-2024

**Comment by seasidesparrow** [comment]
It looks like it should have `%I OPEN` as well

**Comment by csgrant00** [comment]
yes to open. can do html for consistency if you want, but we don't need it
because we use the doi to generate the publisher html link.

C

**Comment by seasidesparrow** [comment]
Does this look ok?

`%I PDF: https://acp.copernicus.org/articles/24/1/2024/acp-24-1-2024.pdf; HTML: https://acp.copernicus.org/articles/24/1/2024/acp-24-1-2024.html; DOI: 10.5194/acp-24-1-2024`

**Comment by csgrant00** [comment]
yes!

*************************************************************************

 Carolyn Stern Grant              Astrophysics Data System (ADS)

 ***@***.***        Center for Astrophysics

 617-495-7154 (voicemail)      60 Garden Street  MS 83

 617-495-7356 fax                 Cambridge, MA  02138

*************************************************************************
